//! Init command implementation.
//!
//! Creates a starter lazytail.yaml config file in the current directory.

use crate::config::discovery::{DATA_DIR_NAME, PROJECT_CONFIG_NAME};
use crate::source;

/// Run the init command.
///
/// Creates a lazytail.yaml config file and .lazytail/ data directory
/// in the current working directory.
///
/// # Arguments
///
/// * `force` - If true, overwrite existing config file
///
/// # Returns
///
/// * `Ok(())` on success
/// * `Err(exit_code)` on failure
pub fn run(force: bool) -> Result<(), i32> {
    // Get current working directory
    let cwd = std::env::current_dir().map_err(|e| {
        eprintln!("error: Failed to get current directory: {}", e);
        1
    })?;

    // Build paths
    let config_path = cwd.join(PROJECT_CONFIG_NAME);
    let data_dir = cwd.join(DATA_DIR_NAME);

    // Check for existing config
    if config_path.exists() && !force {
        eprintln!("error: {} already exists", config_path.display());
        eprintln!("hint: Use --force to overwrite");
        return Err(1);
    }

    // Auto-detect project name from directory
    let project_name = cwd
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "my-project".to_string());

    // Generate config content
    let content = generate_config_template(&project_name);

    // Write config file
    std::fs::write(&config_path, content).map_err(|e| {
        eprintln!("error: Failed to write config: {}", e);
        1
    })?;

    // Create .lazytail/ data directory
    source::create_secure_dir(&data_dir).map_err(|e| {
        eprintln!("error: Failed to create data directory: {}", e);
        1
    })?;

    // Success message
    println!("Created {} and {}/", PROJECT_CONFIG_NAME, DATA_DIR_NAME);
    Ok(())
}

/// Generate the config file template with the given project name.
fn generate_config_template(project_name: &str) -> String {
    format!(
        r#"# lazytail.yaml - Log viewer configuration
# Generated by: lazytail init

# Project name (optional, defaults to directory name)
name: {project_name}

# Log sources to display in the viewer
# sources:
#   - name: api           # Display name shown in tabs
#     path: /var/log/api.log
#   - name: worker
#     path: ~/logs/worker.log
"#,
        project_name = project_name
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_config_template_contains_project_name() {
        let content = generate_config_template("my-app");
        assert!(content.contains("name: my-app"));
    }

    #[test]
    fn test_generate_config_template_has_commented_sources() {
        let content = generate_config_template("test");
        assert!(content.contains("# sources:"));
        assert!(content.contains("#   - name: api"));
    }
}
